import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gebhaly Shop',
  description: 'Generated by create next app',
}

import type { AppProps } from 'next/app';
import { _Provider } from './Redux/Provider';


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <_Provider>
          {children}
        </_Provider>
      </body>
    </html>
  )
}
